theme: minima
title: Hello to my Awesome Site!
author: Jacob Wu
email: jacob.wu@email.com
description: > # this means to ignore newlines until "baseurl:"
  Jacobwu.org

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jacobwu-b # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
