theme: minima
title: Hello to my Awesome Site!
author: Jacob Wu
email: jacob.wu@email.com
description: This is a description

# social links
github_username:  jacobwu-b # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
